### ISSUE TITLE
Error using virtualization

### ISSUE THREAD

**Issue by dacostajose** [tarikcaliskan/react-beautiful-tree#2]
I'm trying to use the virtualization feature, in a app with material-ui, if i try without the property work fine, but if i activated the property, don't work, the error is:

react-beautiful-dnd

A setup problem was encountered.

> Invariant failed: 
provided.innerRef has not been provided with a HTMLElement.

You can find a guide on using the innerRef callback functions at:
https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/using-inner-ref.md

The code is:

```
const renderItem = ({ item, onExpand, onCollapse, provided, snapshot }) => {
        const keysVisibleWorkFlows = visibleWorkflows.map((w) => w.id)
        return (
            <Grid
                {...provided.draggableProps}
                {...provided.dragHandleProps}
                className={classNames(
                    classes.dragContainer,
                    snapshot.isDragging && classes.dragContainerDragging
                )}
                ref={provided.ref}
            >
```

**Comment by atarikcaliskan** [comment]
I think the problem is caused by the `ref` property. Please try to update `ref` like `ref={provided.innerRef}`.
