### ISSUE TITLE
D&D with Multi select items

### ISSUE THREAD

**Issue by ortizman** [tarikcaliskan/react-beautiful-tree#3]
Excellent component. 
I'm a bit advanced with a feature

Does it allow to select more than one item from the tree at the same time?
If the above is possible, is there a way to drag and drop them all together?

**Comment by atarikcaliskan** [comment]
For now, no. But this is a nice feature. I am trying to reduce the bundle size of the library right now. After that, I might add it. Thanks for your feedback 🙌
